Repository OneLiteFeatherNET/Microtus, pull requests merged in 2023-11, with the labels that each got.

#44 Fix loading of 1.20 worlds, update hephaistos to 2.6.1
  minestom-patches/0013-Update-to-1.20.patch
Labels: Bugfix

#51 Update kyori blossom plugin
  minestom-patches/0018-Update-kyori-blossom-plugin.patch
Labels: Feature

#3 Bump dependencies
  minestom-patches/0018-Update-kyori-blossom-plugin.patch
  minestom-patches/0019-Bump-dependencies.patch
Labels: Enhancement, Feature

#52 Update name convention of an ItemStack tag (internally)
  minestom-patches/0020-Rename-name-tag-variable-for-consistency.patch
Labels: Breaking changes, Feature

#53 Improve entity position synchronisation
  minestom-patches/0021-Improve-entity-position-synchronisation.patch
Labels: Bugfix

#54 Update NBT handling for items wihout any NBT data
  minestom-patches/0022-Update-nbt-data-sending-and-reading.patch
Labels: Bugfix

#57 Add a pre compiled pattern to reduce pattern creation
  minestom-patches/0016-Improve-string-pattern-usage.patch
Labels: Bugfix

#56 Add contribution file
  CONTRIBUTING.md
  README.md
Labels: Feature
