Repository OneLiteFeatherNET/Microtus, pull requests merged in 2023-07, with the labels that each got.

#19 Add meta classes for shield and banner
  minestom-patches/0011-Add-banner-pattern-generator.patch
Labels: Enhancement, Feature

#22 Change license to have more afford
  LICENSE
  minestom-patches/0005-Add-github-publishing.patch
Labels: Enhancement, Feature

#16 Feature/1.20 support
  minestom-patches/0013-Update-to-1.20.patch
Labels: Feature, Low Priority, Major feature, on hold, upstream issue

#24 Update entity meta data implmentations
  minestom-patches/0014-Add-metadata-implementation-for-some-entities.patch
Labels: Feature

#26 Remove double registration of the ChatSessionUpdate packet
  minestom-patches/0007-Add-classes-and-modifications-for-1.19.4-ready.patch
Labels: Bugfix
