Repository OneLiteFeatherNET/Microtus, pull requests merged in 2023-12, with the labels that each got.

#63 Add section about how to update a branch
  CONTRIBUTING.md
Labels: documentation, Enhancement, Feature

#64 Improve RegEx usage in the EncryptionResponsePacket
  minestom-patches/0011-Improve-string-pattern-usage.patch
Labels: Enhancement, Feature

#66 Deprecate inventory constructors which takes a string as parameter
  minestom-patches/0015-Update-deprecated-methods.patch
Labels: Feature

#68 Add idea folder to the ignore file
  .gitignore
Labels: Enhancement, Feature

#69 Update version numbers for some dependencies
  minestom-patches/0001-Rework-gradle-management.patch
Labels: Feature

#70 Improve java keyword usage
  minestom-patches/0016-Update-java-keyword-usage.patch
Labels: Enhancement, Feature
