Repository OneLiteFeatherNET/Microtus, pull requests merged in 2024-11, with the labels that each got.

#90 Implement game tags and game events
  code-generators/src/main/java/net/minestom/codegen/Generators.java
  src/autogenerated/java/net/minestom/server/game/GameEvents.java
  src/main/java/net/minestom/server/game/GameEvent.java
  src/main/java/net/minestom/server/game/GameEventImpl.java
  src/main/java/net/minestom/server/gamedata/tags/Tag.java
  src/main/java/net/minestom/server/registry/Registry.java
  src/main/java/net/minestom/server/registry/StaticProtocolObject.java
Labels: Feature

#98 Improve nullability for Minecraft Tags
  src/main/java/net/minestom/server/gamedata/tags/Tag.java
  src/main/java/net/minestom/server/network/packet/server/common/TagsPacket.java
Labels: Bugfix

#97 Add utility method to verify active effects on an entity
  src/main/java/net/minestom/server/entity/Entity.java
  src/test/java/net/minestom/server/entity/EntityEffectIntegrationTest.java
Labels: Feature

#94 task: extract dynamic registries and deprecate old methods
  src/main/java/net/minestom/server/ServerProcess.java
  src/main/java/net/minestom/server/ServerProcessImpl.java
  src/main/java/net/minestom/server/registry/DeprecatedServerProcessDynamicRegistry.java
  src/main/java/net/minestom/server/registry/DynamicRegistries.java
Labels: chore

#102 Add connect method which use a default position
  src/test/java/net/minestom/server/entity/player/PlayerMovementIntegrationTest.java
  src/test/java/net/minestom/server/instance/WeatherTest.java
  testing/src/main/java/net/minestom/testing/TestConnection.java
Labels: Feature

#103 Update Gradle to 8.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Feature
