Repository OneLiteFeatherNET/Microtus, pull requests merged in 2024-02, with the labels that each got.

#86 Restructure code generators
  minestom-patches/0004-1.19-to-1.19.4-Major-update.patch
  minestom-patches/0009-Update-to-1.20.patch
  minestom-patches/0023-Rethink-generator-structure-and-generation.patch
Labels: Feature

#87 Fix failing biome tests
  minestom-patches/0020-Add-better-biome-system.patch
Labels: Bugfix, tests

#88 Add attribute generator
  minestom-patches/0024-Add-attribute-generator.patch
Labels: Breaking changes, Feature, Major bug fix, Major feature, upstream issue

#92 Replacement of dependency getter
  minestom-patches/0019-Replace-dependency-getter.patch
Labels: Feature

#101 Add feature flag generation
  minestom-patches/0019-Add-feature-flag-generation.patch
  minestom-patches/0020-Replace-dependency-getter.patch
Labels: Feature

#108 Rework feature flags
  minestom-patches/0018-Add-feature-flag-generation.patch
  minestom-patches/0019-Replace-dependency-getter.patch
Labels: Enhancement, Breaking changes, Bugfix, Feature, Major bug fix, Major feature, upstream issue

#107 Rework attribute generator and use now registry entries
  minestom-patches/0015-Add-attribute-generator.patch
  minestom-patches/0018-Add-feature-flag-generation.patch
Labels: Breaking changes, Bugfix, Feature, upstream issue
