Repository OneLiteFeatherNET/Microtus, pull requests merged in 2024-01, with the labels that each got.

#67 Integrate world spawn position handling to the Instance class
  minestom-patches/0016-Integrate-world-spawn-position-to-the-instance.patch
Labels: Feature

#72 Fix double used patch index
  minestom-patches/0017-Integrate-world-spawn-position-to-the-instance.patch
Labels: Bugfix

#73 Add bstats support and integration
  minestom-patches/0016-Add-bstats-support-and-integration.patch
  minestom-patches/0017-Update-java-keyword-usage.patch
  minestom-patches/0018-Integrate-world-spawn-position-to-the-instance.patch
Labels: Feature, Major feature

#75 Add extension generation for minestom
  .github/workflows/build.yml
  README.md
  minestom-patches/0019-Add-extension-module.-This-module-allows-us-to-gener.patch
Labels: Feature, Major feature

#76 Add more issue templates
  .github/ISSUE_TEMPLATES/bug.yml
  .github/ISSUE_TEMPLATES/config.yml
  .github/ISSUE_TEMPLATES/feature-request.yml
  .github/ISSUE_TEMPLATES/performance.yml
  README.md
Labels: Feature

#18 Better Biome Support
  minestom-patches/0020-Add-better-biome-system.patch
Labels: Breaking changes, Feature, upstream issue

#80 Update dependencies
  minestom-patches/0001-Rework-gradle-management.patch
  minestom-patches/0016-Add-bstats-support-and-integration.patch
Labels: Feature

#79 Remove deprecated methods
  minestom-patches/0015-Update-deprecated-methods.patch
  minestom-patches/0017-Update-java-keyword-usage.patch
Labels: Breaking changes, Feature

#82 Fix biome id generation and remove optifine support class
  minestom-patches/0020-Add-better-biome-system.patch
Labels: Bugfix

#81 Add support for MiniMessage
  minestom-patches/0001-Rework-gradle-management.patch
  minestom-patches/0016-Add-bstats-support-and-integration.patch
Labels: Feature

#55 Java 21 Update
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  minestom-patches/0001-Rework-gradle-management.patch
  minestom-patches/0021-Upgrade-to-Java-21-as-required.patch
Labels: Feature

#84 Move dependencies from libs.version.toml to settings.gradle.kts
  minestom-patches/0001-Rework-gradle-management.patch
  minestom-patches/0016-Add-bstats-support-and-integration.patch
  minestom-patches/0019-Add-extension-module.-This-module-allows-us-to-gener.patch
Labels: Breaking changes, Feature

#78 Fix switching of entity metadata
  minestom-patches/0022-Fix-switching-of-entity-metadata.patch
Labels: Bugfix

#83 Improve biome ID Order and fix biome particles and color.
  minestom-patches/0020-Add-better-biome-system.patch
Labels: Breaking changes, Bugfix
