Repository OneLiteFeatherNET/Microtus, pull requests merged in 2024-09, with the labels that each got.

#72 Enhance instance and player handling in the test module
  src/test/java/net/minestom/server/instance/InstancePlayerIntegrationTest.java
  testing/src/main/java/net/minestom/testing/Env.java
Labels: documentation, enhancement, Feature

#73 Pull upstream
  gradle/libs.versions.toml
  jcstress-tests/src/jcstress/java/net/minestom/server/tag/TagPathOverrideTest.java
  jcstress-tests/src/jcstress/java/net/minestom/server/tag/TagPathTest.java
  jmh-benchmarks/src/jmh/java/net/minestom/server/tag/TagReadBenchmark.java
  jmh-benchmarks/src/jmh/java/net/minestom/server/tag/TagWriteBenchmark.java
  src/main/java/net/minestom/server/collision/BlockCollision.java
  src/main/java/net/minestom/server/collision/BoundingBox.java
  src/main/java/net/minestom/server/collision/CollisionUtils.java
  src/main/java/net/minestom/server/collision/EntityCollision.java
  src/main/java/net/minestom/server/collision/EntityCollisionResult.java
  src/main/java/net/minestom/server/collision/PhysicsResult.java
  src/main/java/net/minestom/server/collision/PhysicsUtils.java
  src/main/java/net/minestom/server/collision/RayUtils.java
  src/main/java/net/minestom/server/collision/ShapeImpl.java
  src/main/java/net/minestom/server/collision/SweepResult.java
  src/main/java/net/minestom/server/command/CommandManager.java
  src/main/java/net/minestom/server/command/builder/CommandDispatcher.java
  src/main/java/net/minestom/server/component/DataComponentMap.java
  src/main/java/net/minestom/server/coordinate/Vec.java
  src/main/java/net/minestom/server/entity/Entity.java
  src/main/java/net/minestom/server/entity/EquipmentSlot.java
  src/main/java/net/minestom/server/entity/EquipmentSlotGroup.java
  src/main/java/net/minestom/server/entity/LivingEntity.java
  src/main/java/net/minestom/server/entity/Player.java
  src/main/java/net/minestom/server/entity/PlayerProjectile.java
  src/main/java/net/minestom/server/event/EventNodeImpl.java
  src/main/java/net/minestom/server/event/EventNodeLazyImpl.java
  src/main/java/net/minestom/server/instance/Instance.java
  src/main/java/net/minestom/server/instance/LightingChunk.java
  src/main/java/net/minestom/server/instance/Section.java
  src/main/java/net/minestom/server/instance/block/BlockImpl.java
  src/main/java/net/minestom/server/instance/heightmap/Heightmap.java
  src/main/java/net/minestom/server/instance/light/BlockLight.java
  src/main/java/net/minestom/server/instance/light/Light.java
  src/main/java/net/minestom/server/instance/light/LightCompute.java
  src/main/java/net/minestom/server/instance/light/SkyLight.java
  src/main/java/net/minestom/server/inventory/EquipmentHandler.java
  src/main/java/net/minestom/server/inventory/PlayerInventory.java
  src/main/java/net/minestom/server/item/component/Food.java
  src/main/java/net/minestom/server/listener/PlayerPositionListener.java
  src/main/java/net/minestom/server/utils/NamespaceID.java
  src/main/java/net/minestom/server/utils/mojang/MojangUtils.java
  src/test/java/net/minestom/server/ServerProcessTest.java
  src/test/java/net/minestom/server/collision/EntityBlockPhysicsIntegrationTest.java
  src/test/java/net/minestom/server/collision/EntityEntityCollisionIntegrationTest.java
  src/test/java/net/minestom/server/collision/EntityProjectileCollisionIntegrationTest.java
  src/test/java/net/minestom/server/command/CommandParseTest.java
  src/test/java/net/minestom/server/command/CommandSyntaxSingleTest.java
  src/test/java/net/minestom/server/entity/EntityVelocityIntegrationTest.java
  src/test/java/net/minestom/server/entity/player/PlayerMovementIntegrationTest.java
  src/test/java/net/minestom/server/instance/GeneratorIntegrationTest.java
  src/test/java/net/minestom/server/instance/InstanceBlockIntegrationTest.java
  src/test/java/net/minestom/server/instance/anvil/AnvilLoaderIntegrationTest.java
  src/test/java/net/minestom/server/instance/generator/GeneratorForkConsumerIntegrationTest.java
  src/test/java/net/minestom/server/instance/light/BlockLightTest.java
  src/test/java/net/minestom/server/inventory/PlayerInventoryIntegrationTest.java
Labels: Feature

#74 Improve BlockFace usage to avoid unnecessary object creation
  src/main/java/net/minestom/server/collision/ShapeImpl.java
  src/main/java/net/minestom/server/instance/block/BlockFace.java
  src/main/java/net/minestom/server/instance/light/BlockLight.java
  src/main/java/net/minestom/server/instance/light/Light.java
  src/main/java/net/minestom/server/instance/light/SkyLight.java
  src/main/java/net/minestom/server/network/packet/client/play/ClientPlayerDiggingPacket.java
  src/test/java/net/minestom/server/instance/light/BlockIsOccludedTest.java
Labels: Feature

#75 Fix wrong translated enabled features
  src/main/java/net/minestom/server/network/packet/server/configuration/UpdateEnabledFeaturesPacket.java
  src/test/java/net/minestom/server/network/packet/UpdateEnabledFeaturesPacketTest.java
Labels: Feature, Bugfix
