Repository OneLiteFeatherNET/Microtus, pull requests merged in 2024-10, with the labels that each got.

#80 Cache uuid pattern
  src/main/java/net/minestom/server/utils/mojang/MojangUtils.java
Labels: Bugfix, hacktoberfest-accepted

#81 Fix custom player provider usage for junit
  testing/src/main/java/net/minestom/testing/TestConnection.java
  testing/src/main/java/net/minestom/testing/TestConnectionImpl.java
Labels: Bugfix

#86 Fix potential protocol mismatch and exploit for plugin message channel
  src/main/java/net/minestom/server/entity/Player.java
  src/main/java/net/minestom/server/network/packet/server/common/PluginMessagePacket.java
Labels: bug, Bugfix, hacktoberfest, hacktoberfest-accepted

#87 Update from upstream
  build-logic/build.gradle.kts
  code-generators/src/main/java/net/minestom/codegen/Generators.java
  code-generators/src/main/java/net/minestom/codegen/MinestomCodeGenerator.java
  code-generators/src/main/java/net/minestom/codegen/entity/VillagerProfessionGenerator.java
  code-generators/src/main/java/net/minestom/codegen/entity/VillagerTypeGenerator.java
  code-generators/src/main/java/net/minestom/codegen/fluid/FluidGenerator.java
  demo/src/main/java/net/minestom/demo/Main.java
  demo/src/main/java/net/minestom/demo/PlayerInit.java
  src/autogenerated/java/net/minestom/server/color/DyeColor.java
  src/autogenerated/java/net/minestom/server/entity/villager/VillagerProfessions.java
  src/autogenerated/java/net/minestom/server/entity/villager/VillagerTypes.java
  src/autogenerated/java/net/minestom/server/fluid/Fluid.java
  src/autogenerated/java/net/minestom/server/fluid/Fluids.java
  src/autogenerated/java/net/minestom/server/registry/FluidRegistries.java
  src/main/java/net/minestom/server/entity/Player.java
  src/main/java/net/minestom/server/entity/metadata/monster/zombie/ZombieVillagerMeta.java
  src/main/java/net/minestom/server/entity/metadata/villager/VillagerMeta.java
  src/main/java/net/minestom/server/entity/pathfinding/Navigator.java
  src/main/java/net/minestom/server/entity/pathfinding/PNode.java
  src/main/java/net/minestom/server/entity/pathfinding/PPath.java
  src/main/java/net/minestom/server/entity/pathfinding/PathGenerator.java
  src/main/java/net/minestom/server/entity/pathfinding/generators/FlyingNodeGenerator.java
  src/main/java/net/minestom/server/entity/pathfinding/generators/GroundNodeGenerator.java
  src/main/java/net/minestom/server/entity/pathfinding/generators/NodeGenerator.java
  src/main/java/net/minestom/server/entity/pathfinding/generators/PreciseGroundNodeGenerator.java
  src/main/java/net/minestom/server/entity/pathfinding/generators/WaterNodeGenerator.java
  src/main/java/net/minestom/server/entity/villager/VillagerProfession.java
  src/main/java/net/minestom/server/entity/villager/VillagerProfessionImpl.java
  src/main/java/net/minestom/server/entity/villager/VillagerType.java
  src/main/java/net/minestom/server/entity/villager/VillagerTypeImpl.java
  src/main/java/net/minestom/server/event/entity/EntityTeleportEvent.java
  src/main/java/net/minestom/server/event/player/PlayerAnvilInputEvent.java
  src/main/java/net/minestom/server/fluid/Fluid.java
  src/main/java/net/minestom/server/fluid/FluidImpl.java
  src/main/java/net/minestom/server/gamedata/tags/Tag.java
  src/main/java/net/minestom/server/instance/anvil/AnvilLoader.java
  src/main/java/net/minestom/server/instance/block/Block.java
  src/main/java/net/minestom/server/instance/block/BlockHandler.java
  src/main/java/net/minestom/server/instance/block/BlockImpl.java
  src/main/java/net/minestom/server/item/component/Food.java
  src/main/java/net/minestom/server/listener/AnvilListener.java
  src/main/java/net/minestom/server/listener/BlockPlacementListener.java
  src/main/java/net/minestom/server/listener/WindowListener.java
  src/main/java/net/minestom/server/network/NetworkBufferTypeImpl.java
  src/main/java/net/minestom/server/network/player/PlayerConnection.java
  src/main/java/net/minestom/server/registry/Registry.java
  src/main/java/net/minestom/server/tag/Tag.java
  src/main/java/net/minestom/server/thread/TickSchedulerThread.java
  src/test/java/net/minestom/server/InsideTest.java
  src/test/java/net/minestom/server/collision/EntityBlockPhysicsIntegrationTest.java
  src/test/java/net/minestom/server/command/ArgumentTypeTest.java
  src/test/java/net/minestom/server/entity/pathfinding/PathfinderIntegrationTest.java
  src/test/java/net/minestom/server/entity/player/PlayerBlockPlacementIntegrationTest.java
  src/test/java/net/minestom/server/entity/player/PlayerMovementIntegrationTest.java
  src/test/java/net/minestom/server/instance/BlockTest.java
  src/test/java/net/minestom/server/instance/WorldBorderIntegrationTest.java
  src/test/java/net/minestom/server/instance/light/LightParityIntegrationTest.java
  src/test/java/net/minestom/server/inventory/InventoryIntegrationTest.java
  src/test/java/net/minestom/server/network/packet/ClientPluginMessagePacketTest.java
Labels: Feature
