Repository OneLiteFeatherNET/Microtus, pull requests merged in 2024-05, with the labels that each got.

#3 [Gradle Extension] Move source to right folder
  extension/src/main/kotlin/net/onelitefeather/microtus/ExtensionPlugin.kt
  extension/src/main/kotlin/net/onelitefeather/microtus/GenerateExtension.kt
  extension/src/main/kotlin/net/onelitefeather/microtus/models/Extension.kt
  src/main/kotlin/minestom.common-conventions.gradle.kts
  src/main/kotlin/minestom.native-conventions.gradle.kts
  src/main/kotlin/minestom.publishing-conventions.gradle.kts
Labels: Feature

#4 [Docs] Fix docs generation
  code-generators/src/main/java/net/minestom/codegen/feature/FeatureFlagGenerator.java
Labels: documentation, Bugfix

#5 [Chore] Change adventure javadocs link
  build.gradle.kts
Labels: documentation, chore

#6 [Chore] Update gradle to 8.7
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: Feature, chore

#7 [Chore] Remove preview feature
  settings.gradle.kts
Labels: Feature, chore

#8 [Bugfix] Improve version string for bstats
  src/main/java/net/minestom/server/Metrics.java
Labels: Bugfix

#9 [Chore] Improve internal registry handling for implementation creation.
  src/main/java/net/minestom/server/command/builder/arguments/Argument.java
  src/main/java/net/minestom/server/entity/EntityTypeImpl.java
  src/main/java/net/minestom/server/entity/damage/DamageTypeImpl.java
  src/main/java/net/minestom/server/instance/block/BlockImpl.java
  src/main/java/net/minestom/server/item/EnchantmentImpl.java
  src/main/java/net/minestom/server/item/MaterialImpl.java
  src/main/java/net/minestom/server/item/armor/TrimMaterialImpl.java
  src/main/java/net/minestom/server/item/armor/TrimPatternImpl.java
  src/main/java/net/minestom/server/item/banner/BannerPatternImpl.java
  src/main/java/net/minestom/server/particle/ParticleImpl.java
  src/main/java/net/minestom/server/potion/PotionEffectImpl.java
  src/main/java/net/minestom/server/potion/PotionTypeImpl.java
  src/main/java/net/minestom/server/registry/Registry.java
  src/main/java/net/minestom/server/sound/SoundEventImpl.java
  src/main/java/net/minestom/server/statistic/StatisticTypeImpl.java
  src/main/java/net/minestom/server/world/biomes/BiomeImpl.java
Labels: Bugfix, chore

#24 Update snapshot and release version
  .github/README.md
Labels: enhancement, chore

#23 [Chore] Rework attribute system to generice generator
  code-generators/src/main/java/net/minestom/codegen/Generators.java
  code-generators/src/main/java/net/minestom/codegen/attribute/AttributeGenerator.java
  demo/src/main/java/net/minestom/demo/entity/ChickenCreature.java
  src/autogenerated/java/net/minestom/server/attribute/Attributes.java
  src/main/java/net/minestom/server/ServerProcessImpl.java
  src/main/java/net/minestom/server/attribute/Attribute.java
  src/main/java/net/minestom/server/attribute/AttributeImpl.java
  src/main/java/net/minestom/server/attribute/AttributeManager.java
  src/main/java/net/minestom/server/attribute/VanillaAttribute.java
  src/main/java/net/minestom/server/entity/LivingEntity.java
  src/main/java/net/minestom/server/entity/Player.java
  src/main/java/net/minestom/server/entity/pathfinding/PFPathingEntity.java
  src/main/java/net/minestom/server/item/ItemSerializers.java
  src/main/java/net/minestom/server/network/packet/server/play/EntityPropertiesPacket.java
  src/main/java/net/minestom/server/registry/Registry.java
  src/main/java/net/minestom/server/utils/ArrayUtils.java
  src/test/java/net/minestom/server/item/ItemAttributeTest.java
Labels: Feature, chore

#26 [Chore] Replace static enum with generated villager types and professions
  code-generators/src/main/java/net/minestom/codegen/Generators.java
  code-generators/src/main/java/net/minestom/codegen/entity/VillagerProfessionGenerator.java
  code-generators/src/main/java/net/minestom/codegen/entity/VillagerTypeGenerator.java
  src/autogenerated/java/net/minestom/server/entity/villager/VillagerProfessions.java
  src/autogenerated/java/net/minestom/server/entity/villager/VillagerTypes.java
  src/main/java/net/minestom/server/entity/metadata/monster/zombie/ZombieVillagerMeta.java
  src/main/java/net/minestom/server/entity/metadata/villager/VillagerMeta.java
  src/main/java/net/minestom/server/entity/villager/VillagerProfession.java
  src/main/java/net/minestom/server/entity/villager/VillagerProfessionImpl.java
  src/main/java/net/minestom/server/entity/villager/VillagerType.java
  src/main/java/net/minestom/server/entity/villager/VillagerTypeImpl.java
  src/main/java/net/minestom/server/registry/Registry.java
Labels: Feature, chore

#31 Bump snapshot version
  build.gradle.kts
Labels: Feature, chore

#32 [Bugfix] Fix some failing tests
  src/test/java/net/minestom/server/instance/AnvilLoaderIntegrationTest.java
  src/test/java/net/minestom/server/item/ItemAttributeTest.java
Labels: Bugfix, tests

#27 [Chore] Replace enum with code generator for fluids
  code-generators/src/main/java/net/minestom/codegen/Generators.java
  code-generators/src/main/java/net/minestom/codegen/fluid/FluidGenerator.java
  src/autogenerated/java/net/minestom/server/fluid/Fluid.java
  src/autogenerated/java/net/minestom/server/fluid/Fluids.java
  src/autogenerated/java/net/minestom/server/registry/Registries.java
  src/main/java/net/minestom/server/fluid/Fluid.java
  src/main/java/net/minestom/server/fluid/FluidImpl.java
  src/main/java/net/minestom/server/gamedata/tags/Tag.java
  src/main/java/net/minestom/server/registry/Registry.java
Labels: enhancement, chore

#28 [Chore] Replace enum with registry system for feature flags
  code-generators/src/main/java/net/minestom/codegen/Generators.java
  code-generators/src/main/java/net/minestom/codegen/feature/FeatureFlagGenerator.java
  settings.gradle.kts
  src/autogenerated/java/net/minestom/server/feature/FeatureFlags.java
  src/autogenerated/java/net/minestom/server/featureflag/FeatureFlags.java
  src/main/java/net/minestom/server/event/player/AsyncPlayerConfigurationEvent.java
  src/main/java/net/minestom/server/featureflag/FeatureFlag.java
  src/main/java/net/minestom/server/featureflag/FeatureFlagImpl.java
  src/main/java/net/minestom/server/network/packet/server/configuration/UpdateEnabledFeaturesPacket.java
  src/main/java/net/minestom/server/registry/Registry.java
Labels: Feature, chore

#29 [Chore] Replace e.printstacktrace with exception manager call or logger
  src/main/java/net/minestom/server/entity/PlayerProjectile.java
  src/main/java/net/minestom/server/exception/ExceptionManager.java
  src/main/java/net/minestom/server/extras/velocity/VelocityProxy.java
  src/main/java/net/minestom/server/instance/AnvilLoader.java
  src/main/java/net/minestom/server/instance/batch/ChunkBatch.java
  src/main/java/net/minestom/server/network/socket/Server.java
  src/main/java/net/minestom/server/tag/TagNbtSeparator.java
  src/main/java/net/minestom/server/terminal/MinestomTerminal.java
Labels: chore

#37 Comment out gameevent tags and fix order of AtomicInteger for fluid registry
  src/main/java/net/minestom/server/fluid/FluidImpl.java
  src/main/java/net/minestom/server/gamedata/tags/Tag.java
Labels: Bugfix

#35 [#34] Better Notification System
  demo/src/main/java/net/minestom/demo/PlayerInit.java
  demo/src/main/java/net/minestom/demo/commands/NotificationCommand.java
  src/main/java/net/minestom/server/advancements/AdvancementTab.java
  src/main/java/net/minestom/server/advancements/notifications/Notification.java
  src/main/java/net/minestom/server/advancements/notifications/NotificationCenter.java
  src/main/java/net/minestom/server/notifications/Notification.java
  src/main/java/net/minestom/server/notifications/NotificationBuilder.java
  src/main/java/net/minestom/server/notifications/NotificationImpl.java
  src/main/java/net/minestom/server/notifications/package-info.java
  src/test/java/net/minestom/server/notifications/NotificationIntegrationTest.java
Labels: Feature
